# Generated by Django 4.1 on 2022-09-04 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=32, verbose_name='Loan type')),
                ('loan_description', models.TextField(verbose_name='Loan Description')),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('gender', models.CharField(max_length=6, verbose_name='Gender')),
                ('address', models.TextField(verbose_name='Address')),
                ('aadhaar', models.ImageField(upload_to='', verbose_name='Aadhaar photo')),
                ('status', models.CharField(choices=[('AP', 'Approved'), ('PE', 'Pending'), ('DE', 'Declined')], default='PE', max_length=2)),
                ('comments', models.TextField(verbose_name='Comments on loan status')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Applicant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
